services:
  app:
    build: .
    ports:
      - "18080:80"
    depends_on:
      - db

  db:
    image: postgres:17.2
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: alterna
    ports:
      - "5432:5432"

volumes:
  db_data:
