openapi: 3.0.1

info:
  title: alterna
  version: 0.0.1

paths:
  /sumishin:
    get:
      summary: 住信sbiの最新情報取得 for frontend
      operationId: getSumishinLatest
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/sumishin"

components:
  schemas:
    sumishin:
      type: object
      properties:
        balance:
          type: number
