[project]
name = "alterna"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.6",
    "python-dotenv>=1.0.1",
    "selenium>=4.27.1",
]
